### ISSUE TITLE
Options (release gaze, start tracking, stop, start ....) inactive 

### ISSUE THREAD

**Issue by MustafaHasria** [visualcamp/seeso-sample-android#20] opened 2022-08-11 09:08 UTC
Hi there 

I just have a small issue after I cloned the project and set AAR files I ran the app and it's worked fine.
but the buttons (Release gaze, start tracking, and others don't work except (Init Gaze, Gaze path demo)
Any idea can help me 

Thanks in advance.

**Comment by MustafaHasria** [comment] 2022-08-11 09:16
Sorry I just forgot to set the SEESO_LICENSE_KEY

**Comment by Dabin22** [comment] 2022-08-12 01:36
The issue is closed as it has been resolved.

**Closed as completed by Dabin22** 2022-08-12 01:36 UTC
Labels: help wanted
